import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:flutter_map/flutter_map.dart';
import 'package:latlong2/latlong.dart';
import 'dart:isolate'; 
import 'dart:convert'; 
import 'package:http/http.dart' as http;

import '../models/earthquake_event.dart';

class EarthquakeService {
  
  static Future<List<EarthquakeEvent>> loadEarthquakes() async {
    try {
      // 1. Point this exactly to the new CSV file generated by Python
      final String csvString = await rootBundle.loadString('assets/Earthquake_Cat.csv');
      
      return await Isolate.run(() => _parseCsvInBackground(csvString));
    } catch (e) {
      debugPrint("Error loading earthquake CSV: $e");
      return []; // Return empty list so the app doesn't crash if file is missing
    }
  }

  static List<EarthquakeEvent> _parseCsvInBackground(String csvString) {
    List<EarthquakeEvent> events = [];
    List<String> lines = const LineSplitter().convert(csvString);
    
    bool firstRow = true;
    for (String line in lines) {
      if (firstRow) {
        firstRow = false; 
        continue;
      }
      
      if (line.trim().isEmpty) continue;

      List<String> row = line.split(',');
      if (row.length >= 6) {
        final lat = double.tryParse(row[1].trim());
        final lng = double.tryParse(row[0].trim());
        final mag = double.tryParse(row[5].trim());
        String formattedDate = "Unknown Date";

        // Extract Date components (Indices 2: Year, 3: Month, 4: Day)
        final double? rawYear = double.tryParse(row[2].trim());
        String month = row[3].trim();
        String day = row[4].trim();

        if (rawYear != null) {
          // Round the fractional year to the nearest whole integer
          int yearInt = rawYear.round();

          // Format as DD/MM/YYYY, handling negative years as BC
          if (yearInt < 0) {
            formattedDate = "$day/$month/${yearInt.abs()} BC";
          } else {
            formattedDate = "$day/$month/$yearInt";
          }
        }

        // The CSV sometimes has years like "-2600.0". Let's clean that up so it looks nicer.
    

        if (lat != null && lng != null && mag != null) {
          // Pass the formatted date into the model!
          events.add(EarthquakeEvent(
            LatLng(lat, lng), 
            mag, 
            date: formattedDate,
          ));
        }
      }
    }
    return events;
  }

  static Color _getMagnitudeColor(double magnitude) {
    if (magnitude >= 9.0) return Colors.purple[800]!.withOpacity(0.9); 
    if (magnitude >= 8.0) return Colors.red[900]!.withOpacity(0.9);    
    if (magnitude >= 7.0) return Colors.red.withOpacity(0.9);          
    if (magnitude >= 6.0) return Colors.deepOrange.withOpacity(0.9);   
    if (magnitude >= 5.5) return Colors.orange[800]!.withOpacity(0.9); // New 5.5 step
    if (magnitude >= 5.0) return Colors.orange[400]!.withOpacity(0.9); // Adjusted 5.0 step
    if (magnitude >= 4.5) return Colors.yellow[700]!.withOpacity(0.8); // New 4.5 step
    return Colors.yellow[300]!.withOpacity(0.7);                       // 4.0 to 4.4
  }

  static Color _getMagnitudeBorderColor(double magnitude) {
    if (magnitude >= 9.0) return Colors.purple[900]!;
    if (magnitude >= 8.0) return Colors.red[900]!;
    if (magnitude >= 7.0) return Colors.red[800]!;
    if (magnitude >= 6.0) return Colors.deepOrange[800]!;
    if (magnitude >= 5.5) return Colors.orange[900]!;
    if (magnitude >= 5.0) return Colors.orange[700]!;
    if (magnitude >= 4.5) return Colors.yellow[800]!;
    return Colors.yellow[600]!; 
  }
  static Future<List<EarthquakeEvent>> fetchRecentEarthquakes() async {
    try {
      // Calculate date 7 years ago
      final startDate = DateTime.now().subtract(const Duration(days: 7)).toIso8601String();
      
      // USGS API with Bounding Box for India region to prevent massive payload crashing the app
      final url = Uri.parse(
          'https://earthquake.usgs.gov/fdsnws/event/1/query?format=geojson&starttime=$startDate&minmagnitude=4.0&minlatitude=6.7&maxlatitude=37.0&minlongitude=68.0&maxlongitude=97.4'
      );

      final response = await http.get(url);
      
      if (response.statusCode == 200) {
        return await Isolate.run(() => _parseGeoJsonInBackground(response.body));
      } else {
        debugPrint("USGS API Error: ${response.statusCode}");
        return [];
      }
    } catch (e) {
      debugPrint("Error fetching USGS earthquakes: $e");
      return [];
    }
  }

  static List<EarthquakeEvent> _parseGeoJsonInBackground(String jsonString) {
    List<EarthquakeEvent> events = [];
    final data = json.decode(jsonString);
    final features = data['features'] as List;

    for (var feature in features) {
      final props = feature['properties'];
      final geom = feature['geometry'];

      final mag = (props['mag'] as num?)?.toDouble() ?? 4.0;
      final coords = geom['coordinates'] as List;
      final lng = (coords[0] as num).toDouble();
      final lat = (coords[1] as num).toDouble();
      final timeEpoch = props['time'] as int?;

      String formattedDate = "Unknown Date";
      if (timeEpoch != null) {
        final date = DateTime.fromMillisecondsSinceEpoch(timeEpoch);
        formattedDate = "${date.day}/${date.month}/${date.year}";
      }

      events.add(EarthquakeEvent(LatLng(lat, lng), mag, date: formattedDate));
    }
    return events;
  }

  static List<CircleMarker> buildMarkers(List<EarthquakeEvent> earthquakes) {
    final sortedEq = List<EarthquakeEvent>.from(earthquakes)
      ..sort((a, b) => a.magnitude.compareTo(b.magnitude));
    return sortedEq
        .where((e) => e.magnitude >= 4.0) 
        .map(
          (e) => CircleMarker(
            point: e.location,
            color: _getMagnitudeColor(e.magnitude),
            borderColor: _getMagnitudeBorderColor(e.magnitude),
            borderStrokeWidth: 1.5,
            radius: 7.0,
          ),
        )
        .toList();
  }
  
}